# This file uses the new configuration format for golangci-lint v2.x
# See https://golangci-lint.run/usage/configuration/ for full docs

version: 2

run:
  timeout: 5m

linters:
  disable-all: true
  disable:
    - errcheck
    - staticcheck
  enable:
    - misspell
    - govet
    - ineffassign
    - unused
    - revive

issues:
  exclude-use-default: false
  exclude:
    - 'should have a package comment'
    - 'comment on exported method'
    - 'should have comment or be unexported'
    - 'error strings should not be capitalized or end with punctuation or a newline'
